version: '3'
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: server
    ports:
      - '5000:3000'
    networks:
      - mern-app
    links:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    networks:
      - mern-app
networks:
    mern-app:
      driver: bridge